### ISSUE TITLE
Simulation crash

### ISSUE THREAD

**Issue by AetherDim** [AetherDim/RoboRAVE-Cyberspace#2]
This code will produce an error while simulating (probably due to a wrong robot config):

http://localhost:1999/#loadProgram&&ev3lejosv1&&NEPOprog&&%3Cexport%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%3E%3Cprogram%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22ev3%22%20xmlversion=%223.0%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%2224%22%20y=%222%22%3E%3Cblock%20type=%22robControls_start%22%20id=%22)1i%25@NSw,z9G@00b4f!#%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cmutation%20declare=%22false%22%3E%3C/mutation%3E%3Cfield%20name=%22DEBUG%22%3EFALSE%3C/field%3E%3C/block%3E%3Cblock%20type=%22robControls_loopForever%22%20id=%223p8m%25h%7DJSlS0/XX/M,ED%22%20intask=%22true%22%3E%3Cstatement%20name=%22DO%22%3E%3Cblock%20type=%22robControls_if%22%20id=%22b6%7CB+%5DzW%5DK%7BGnJj%5Dz8I#%22%20intask=%22true%22%3E%3Cvalue%20name=%22IF0%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22VR(e_?p=@X#gtFnmo-:%7D%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22.l%7CTb%609(o%5EdizkCbT%5BV%5E%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E2%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22b30_U-1Kvgfpr3JXvvx/%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#000000%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO0%22%3E%3Cblock%20type=%22robActions_motorDiff_on%22%20id=%22j1nOGXljAT+irosOyi0o%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3EFOREWARD%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22oCq-S02DKdN%5E0%25nXjzzV%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E30%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robControls_if%22%20id=%22NR%5DDyI:a%7DGqr%7B%7Dy6oGX7%22%20intask=%22true%22%3E%3Cvalue%20name=%22IF0%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22E%7B=7)%7Cun#s03(N,SDp=~%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22nr_NX:p0)oJ%7Dy*Va*k84%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E3%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22#FIN3pY*%7BFO#++*a9%5B0Y%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#000000%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO0%22%3E%3Cblock%20type=%22robActions_motorDiff_turn%22%20id=%223sYh9aaY%7DEi(DI9%7DjBkF%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3ERIGHT%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22:wKG)%7Di(y%7D%5E49u=39HyN%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E25%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robControls_if%22%20id=%22rpeq7+%7Bqaa?T78-gYG3I%22%20intask=%22true%22%3E%3Cvalue%20name=%22IF0%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22W*Rwsk-s%5B,A9EZtrLMVh%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22@w+r@:et?iw?C6C1qk:1%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E1%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22~dKQVZoi-ZS%7BNMJ%7D_HsY%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#000000%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO0%22%3E%3Cblock%20type=%22robActions_motorDiff_turn%22%20id=%22X?i%5B6v:h7%60O0UA7_aQau%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3ELEFT%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22iHRxci4%7C7aUQz4T:JX9T%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E25%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robControls_if%22%20id=%22K.I-nvPffKw%5Bl%7B*IWzn8%22%20intask=%22true%22%3E%3Cvalue%20name=%22IF0%22%3E%3Cblock%20type=%22logic_operation%22%20id=%22)x/#tJ@3pJw/#h-~!m8a%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EAND%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22=p%60?041Rqa/.(dv@H%7B1%7B%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22q=%60!*%7D9nLM;:R_VPJQGD%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E2%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22QUxMw8x3AR))iZh4:N%7B,%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#000000%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22ybMh%7C6%7BDc0O3tblCw%5E%5EK%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22EB-zv0%60PAPa%25bA%60G,A/=%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E1%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22,o0qrSOM.+mB)i51?Bgz%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#585858%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO0%22%3E%3Cblock%20type=%22robActions_motorDiff_turn_for%22%20id=%22%7CTmA@!y7)(zdEx:%5E.%5BbL%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3ERIGHT%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%2250%5Bv.c?.r1yjF-gMn%60Ku%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E25%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22DEGREE%22%3E%3Cblock%20type=%22math_number%22%20id=%22%7Dun#-(?s0za59PO%25x8vn%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E45%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3Cblock%20type=%22robActions_motorDiff_on%22%20id=%22;L6L)CD!h_.%5B);Pf%250%5E%25%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3EFOREWARD%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22?FxUg-%606(4:Rhf_k~4vU%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E30%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3Cblock%20type=%22robControls_wait_time%22%20id=%22gpE)9u~eh:M-Wq%5E1%7C.5%7C%22%20intask=%22true%22%3E%3Cvalue%20name=%22WAIT%22%3E%3Cblock%20type=%22math_number%22%20id=%22g+P1st;_KHA+b64ELgoD%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E700%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robControls_if%22%20id=%22p@8_%60Zog)rHlQg@NCIu)%22%20intask=%22true%22%3E%3Cvalue%20name=%22IF0%22%3E%3Cblock%20type=%22logic_operation%22%20id=%22faQJN;N.18+@nH,==%60;~%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EAND%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22mn*OV(v)).cOpoiQ.6H5%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22d1uDLdO%5BYM4SY4dQy#b/%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E2%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22(Zcu!WBP#6sRuQ6dBiM@%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#585858%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22bH_Zn%5B*%25%5B2%5D6+)u;hEXS%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22(#Yego8;4_QVF1%5D~+%5E2:%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E1%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%225%5D3gZ~A/JIxIZ+;neKPr%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#000000%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO0%22%3E%3Cblock%20type=%22robActions_motorDiff_turn_for%22%20id=%22=z3IezyhHNLZxHV%60hu8L%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3ERIGHT%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22qOuZb@h5yUf%7D8-JhL~jf%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E25%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22DEGREE%22%3E%3Cblock%20type=%22math_number%22%20id=%22*)P?b9HpxI5VMB%25%7B%60Np,%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E45%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3Cblock%20type=%22robActions_motorDiff_on%22%20id=%22Slh.@C4y(-M~c*Yl9F!r%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3EFOREWARD%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22/%60dc%5D.yZ0Ghj/R3M81h%5E%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E30%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3Cblock%20type=%22robControls_wait_time%22%20id=%22,%5DW%5BA=hz=UnopKtkJD.L%22%20intask=%22true%22%3E%3Cvalue%20name=%22WAIT%22%3E%3Cblock%20type=%22math_number%22%20id=%22XzcAA)8C0*jl#J3tf9Ad%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E700%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3Cblock%20type=%22robControls_if%22%20id=%22c~J;Ol%60Cvkn?BuZ7Cz8i%22%20intask=%22true%22%3E%3Cvalue%20name=%22IF0%22%3E%3Cblock%20type=%22logic_operation%22%20id=%22FxI86%5E0+/4.fmtle0We#%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EAND%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22V.=DK:O#R6N7?j%7D.%25?O3%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22U.hx%7D0:S)j3HE)bH.1**%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E2%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22krxTY48OFTUiO*g=2rt1%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#585858%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22logic_compare%22%20id=%22o%60nE8Mo4QjO2c5.Wv9kL%22%20intask=%22true%22%3E%3Cfield%20name=%22OP%22%3EEQ%3C/field%3E%3Cvalue%20name=%22A%22%3E%3Cblock%20type=%22robSensors_colour_getSample%22%20id=%22p@7%25:t%5BlIVCQpLbU.g*%25%22%20intask=%22true%22%3E%3Cmutation%20mode=%22COLOUR%22%3E%3C/mutation%3E%3Cfield%20name=%22MODE%22%3ECOLOUR%3C/field%3E%3Cfield%20name=%22SENSORPORT%22%3E1%3C/field%3E%3Cfield%20name=%22SLOT%22%3E%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22B%22%3E%3Cblock%20type=%22robColour_picker%22%20id=%22@%60ewcI%7D?yhn2xz~RD;Rf%22%20intask=%22true%22%3E%3Cfield%20name=%22COLOUR%22%3E#000000%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/value%3E%3Cstatement%20name=%22DO0%22%3E%3Cblock%20type=%22robActions_motorDiff_turn_for%22%20id=%229%7BF_x%7Dq@U6H%5BAykWq(%25w%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3ERIGHT%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22eR8-3pTqf+eEaPuS%5BELm%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E25%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22DEGREE%22%3E%3Cblock%20type=%22math_number%22%20id=%225fWe#7V!vPpnwn98%25!N;%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E45%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3Cblock%20type=%22robActions_motorDiff_on%22%20id=%22?JQ/2Wjn-2/e*PJ77kzN%22%20intask=%22true%22%3E%3Cfield%20name=%22DIRECTION%22%3EFOREWARD%3C/field%3E%3Cvalue%20name=%22POWER%22%3E%3Cblock%20type=%22math_number%22%20id=%22pIS.Q=s8P%7Dzwem%7Cbti2v%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E30%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3Cblock%20type=%22robControls_wait_time%22%20id=%22%5D5%5DDjde=J+z*%5Dx,u*bSK%22%20intask=%22true%22%3E%3Cvalue%20name=%22WAIT%22%3E%3Cblock%20type=%22math_number%22%20id=%22Imy%25jYC69B%7CN#JdF%5B?/T%22%20intask=%22true%22%3E%3Cfield%20name=%22NUM%22%3E700%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3C/statement%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/program%3E%3Cconfig%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22ev3%22%20xmlversion=%223.0%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%22213%22%20y=%22213%22%3E%3Cblock%20type=%22robBrick_EV3-Brick%22%20id=%221%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cfield%20name=%22WHEEL_DIAMETER%22%3E5.6%3C/field%3E%3Cfield%20name=%22TRACK_WIDTH%22%3E18%3C/field%3E%3Cvalue%20name=%22S1%22%3E%3Cblock%20type=%22robBrick_colour%22%20id=%22%5BRkxng-e5(niSpAT*1,%25%22%20intask=%22true%22%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22S2%22%3E%3Cblock%20type=%22robBrick_colour%22%20id=%22by%5E0ok%258NVN6(7:jMn+t%22%20intask=%22true%22%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22S3%22%3E%3Cblock%20type=%22robBrick_colour%22%20id=%22E1MZ%7B8Y)gcsF8?=~(-#.%22%20intask=%22true%22%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22S4%22%3E%3Cblock%20type=%22robBrick_ultrasonic%22%20id=%225%22%20intask=%22true%22%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22MB%22%3E%3Cblock%20type=%22robBrick_motor_big%22%20id=%226%22%20intask=%22true%22%3E%3Cfield%20name=%22MOTOR_REGULATION%22%3ETRUE%3C/field%3E%3Cfield%20name=%22MOTOR_REVERSE%22%3EOFF%3C/field%3E%3Cfield%20name=%22MOTOR_DRIVE%22%3ERIGHT%3C/field%3E%3C/block%3E%3C/value%3E%3Cvalue%20name=%22MC%22%3E%3Cblock%20type=%22robBrick_motor_big%22%20id=%227%22%20intask=%22true%22%3E%3Cfield%20name=%22MOTOR_REGULATION%22%3ETRUE%3C/field%3E%3Cfield%20name=%22MOTOR_REVERSE%22%3EOFF%3C/field%3E%3Cfield%20name=%22MOTOR_DRIVE%22%3ELEFT%3C/field%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/config%3E%3C/export%3E

**Comment by Qbyte248** [comment]
This issue was fixed by
- 3c78c33297896856c2452f67b4c247682425483b: Add robot configuration setup
- dd9df3cdba29f738e621631cf9f1adae8e82147c: Fix loading of configurations with a URL
- 7e653f56dde8898df29ec65efb25fe3dae673896: Fix loading of configurations with a URL for play/stop button
