### ISSUE TITLE
Add quadro score scene

### ISSUE THREAD

**Issue by AetherDim** [AetherDim/RoboRAVE-Cyberspace#8]

**Comment by Qbyte248** [comment]
The quadro score scene is implemented in commits (only the main ones):
- c48a78e5fbbe80dc9b2f177d58849c72714a4a8d Add MultiCyberspace
- 9ead04d684d89cc23c533e9685d1ceda50963786 Add group name div to html
- 1286d2f8ab4b8979882f6898d840cf4067f5671e Added multi cyberspace view (and connection to REST API)
